//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmlSmartLocker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmlSystemAEntities : DbContext
    {
        public SmlSystemAEntities()
            : base("name=SmlSystemAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TD_FDP1111> TD_FDP1111 { get; set; }
        public virtual DbSet<TD_FDP1115> TD_FDP1115 { get; set; }
    }
}
