//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmlSmartLocker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_FDP1111
    {
        public decimal SEQNO { get; set; }
        public Nullable<System.DateTime> SCN_IND { get; set; }
        public Nullable<System.DateTime> SCN_INT { get; set; }
        public Nullable<decimal> SCN_INPIC { get; set; }
        public Nullable<System.DateTime> SCN_OUTD { get; set; }
        public Nullable<System.DateTime> SCN_OUTT { get; set; }
        public Nullable<decimal> SCN_OUTPIC { get; set; }
        public string LOTNO { get; set; }
        public string RKEIM { get; set; }
        public Nullable<decimal> THEO_QTY { get; set; }
        public Nullable<decimal> ACT_QTY { get; set; }
        public Nullable<decimal> SCN_INQ { get; set; }
        public Nullable<decimal> SCN_OUTQ { get; set; }
        public Nullable<System.DateTime> KSNDAT { get; set; }
        public Nullable<System.DateTime> KSNTIM { get; set; }
        public Nullable<int> FLG1 { get; set; }
        public string LOC_NO { get; set; }
        public Nullable<int> PUT_IN { get; set; }
        public Nullable<System.DateTime> PUT_DATE { get; set; }
        public Nullable<System.DateTime> PUT_TIME { get; set; }
        public Nullable<decimal> PUT_PIC { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public Nullable<System.DateTime> OUT_TIME { get; set; }
        public Nullable<decimal> OUT_PIC { get; set; }
        public Nullable<decimal> TANSUU { get; set; }
    }
}
