//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmlSmartLocker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_FDP1115
    {
        public string CAB { get; set; }
        public string RACK { get; set; }
        public string PLACE { get; set; }
        public string NMODEL { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> LIMIT { get; set; }
        public Nullable<decimal> TQTY { get; set; }
    }
}
